name=PHMonitor
version=1.0.2
author=Manish Kumar Das
maintainer=Manish Kumar Das
sentence=Arduino library for pH monitoring and calibration.
paragraph=Supports pH reading, temperature compensation, OLED and LCD display examples.
category=Sensors
url=https://github.com/ManishKDtm/PHMonitor
architectures=*
