name=PHMonitor
version=1.0.3
author=Manish KD
maintainer=Manish KD <dmanishkumar093@gmail.com>
sentence=Arduino library for pH sensor reading, calibration and temperature compensation.
paragraph=Supports pH reading, temperature compensation, OLED and LCD display examples.
category=Sensors
url=https://github.com/ManishKDtm/PHMonitor
architectures=*
