name=PHMonitor
version=1.0.0
author=Manish Kumar Das
maintainer=Manish Kumar Das
sentence=Water pH monitoring library
paragraph=Supports Arduino, ESP8266 and ESP32 with calibration, temperature compensation, OLED and LCD display.
category=Sensors
architectures=* 